db.driver=com.mysql.cj.jdbc.Driver

db.url=jdbc:mysql://localhost:3306/mutualfundinvestment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

db.username=root

db.password=samsung